repository:
  description: something cool this way comes

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts: [ci]
      enforce_admins: true
      required_linear_history: true
      restrictions: null